### ISSUE TITLE
when "_setContentCompletion":false , icon turns green immediately

### ISSUE THREAD

**Issue by RosiniB** [BATraining/adapt-embeddedLink#27]
if content completion is set to false, the expectation is the icon will remain blue until the callback function in the content is triggered. 

If the content did not have a callback function trigger, the expectation is if set to false then the icon remains blue, will never turn green.

Only when "_setContentCompletion":true will the icon turn green on its own when in view, which currently works as expected.

**Comment by ratnadeeprajput** [comment]
@RosiniB - for false condition it will work as mentioned above. Please review the PR: https://github.com/BATraining/adapt-embeddedLink/pull/28

Hope this works as required.

**Comment by RosiniB** [comment]
it works, thanks.
