### ISSUE TITLE
zoom in button is not correct

### ISSUE THREAD

**Issue by RosiniB** [BATraining/adapt-embeddedLink#37]
when an image is used to popup the link given as source, the button icon in bottom right corner is not showing correctly:
![image](https://user-images.githubusercontent.com/11756914/28972027-294a7ebe-78fc-11e7-8e58-9c175649c7ef.png)

the icon should appear the same as when the source link only is used, as seen here:
![image](https://user-images.githubusercontent.com/11756914/28972072-4e5b47ba-78fc-11e7-973d-7a6809232638.png)

**Comment by ratnadeeprajput** [comment]
@RosiniB - Resolved. PR: https://github.com/BATraining/adapt-embeddedLink/pull/42

**Comment by RosiniB** [comment]
Thank you!
